name: Deploy Frontend to Azure Web App

on:
  push:
    branches:
      - main # main ブランチにプッシュされたときに実行

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # コードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v2

      # Node.js をセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # 使用する Node.js のバージョン（Next.js 推奨: 16 以上）

      # 依存関係のインストール
      - name: Install dependencies
        run: npm install

      # Next.js アプリのビルド
      - name: Build Next.js app
        run: npm run build

      # 必要に応じて、静的エクスポートを実行（オプション）
      # - name: Export Next.js app (Optional)
      #   run: npm run export

      # ビルド成果物を Azure にデプロイ
      - name: Deploy to Azure Web App
        uses: Azure/webapps-deploy@v2
        with:
          app-name: <your-app-name> # Azure App Service の名前を指定
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: . # プロジェクト全体をデプロイする（最適化済み）

# name: Deploy Frontend to Azure Web App

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '18'

#       - name: Install dependencies
#         working-directory: ./frontend/src/app # 正しいディレクトリに設定
#         run: |
#           npm install

#       - name: Build Next.js app
#         working-directory: ./frontend/src/app # 正しいディレクトリに設定
#         run: |
#           npm run build

#       - name: Deploy to Azure
#         uses: azure/webapps-deploy@v2
#         with:
#           app-name: "tech0-gen-9-step3-1-node-72"
#           publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

